__default__:
    h_vmem: 4G
    h_rt:   1:0:0
    pe: smp 1
    R:  y
generate_genome:
    h_vmem:    4G
    tmem:   4G
    h_rt: 72:00:00
    pe: smp 8
fastqc:
    h_vmem:    4G
    tmem:   4G
    h_rt: 72:00:00
multiqc:
    h_vmem:    4G
    tmem:   4G
    h_rt: 72:00:00
fastp_trimming:
    h_vmem:    4G
    tmem:   4G
    h_rt: 72:00:00
run_star_first_pass:
    h_vmem:   8G
    tmem:   8G
    pe: smp 4
    h_rt: 72:00:00
run_star_pe:
    h_vmem:   10G
    tmem:   10G
    pe: smp 4
    h_rt: 72:00:00
run_star_se:
    h_vmem:   8G
    tmem:   8G
    pe: smp 4
    h_rt: 72:00:00
sort_index_bams:
    h_vmem:   1.9G
    tmem:   1.9G
    h_rt: 72:00:00
sort_bams:
    h_vmem:   1.9G
    tmem:   1.9G
    h_rt: 72:00:00
run_slam_dunk:
    h_vmem:    4G
    tmem:   4G
    pe: smp 4
    h_rt: 72:00:00
