######UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
######UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
######UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
#path to a csv with the follwing format: 
#sample_name,unit, fast1,fast2
# if the data is single end leave the fast2 column blank
sampleCSVpath: /SAN/vyplab/alb_projects/data/muscle/wide_fastq.csv
end_type: pe
species: "human"
fastqc_output_folder: /SAN/vyplab/alb_projects/data/muscle/analysis/fastqc/
fastp_trimmed_output_folder: /SAN/vyplab/alb_projects/data/muscle/analysis/fastp_trimmed_again/
#star_output_folder: /SAN/vyplab/alb_projects/data/muscle/analysis/STAR_aligned/
star_output_folder: /SAN/vyplab/alb_projects/data/muscle/analysis/STAR_aligned_two_pass_basic/

# # #####UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
# # #####UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
# sampleCSVpath: /SAN/vyplab/alb_projects/data/4su_tdp_f210i/fastq_locations_4su.csv
# end_type: se
# #mouse or human
# species: "mouse"
# fastqc_output_folder: /SAN/vyplab/alb_projects/data/4su_tdp_f210i/STAR_aligned/fastqc/
# fastp_trimmed_output_folder: /SAN/vyplab/alb_projects/data/4su_tdp_f210i/fastp_trimmed/
# star_output_folder: /SAN/vyplab/alb_projects/data/4su_tdp_f210i/STAR_aligned_two_pass_redone/


######IF YOU DON'T KNOW WHAT YOU'RE DOING DON'T FIDDLE WITH THESE NEXT LINES#########
######IF YOU DON'T KNOW WHAT YOU'RE DOING DON'T FIDDLE WITH THESE NEXT LINES#########
######IF YOU DON'T KNOW WHAT YOU'RE DOING DON'T FIDDLE WITH THESE NEXT LINES#########

#########################
##FASTQC PARAMETERS######
#########################

#path to the fastqc executable
fastqc_path: /share/apps/genomics/fastqc-0.11.2/fastqc



#########################
##FASTP PARAMETERS - TRIMMING HERE######
#########################
fastp_path: /SAN/vyplab/alb_projects/tools/fastp

#quality trimming is debated, and harsh cutoff can effect expression, using a soft quality trim of 10 based on this paper
#https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-0956-2
#use this flag if there are UMI's present, if there are, there should be a file with fastq & umi fastq present, otherwise 
#additional parameters you might want to add on
fastp_parameters:
  qualified_quality_phred: 10
  #use this flag if there are UMI's present, if there are, there should be a file with fastq & umi fastq present, otherwise 
  #leave this flag as an empty string: ""
  #umi: ""
  #umi_loc: /SAN/vyplab/IoN_RNAseq/Bilal_Muscle_biopsies/analysis/fastqc/


#########################
##STAR PARAMETERS - ALIGNMENT HERE######
#########################
#location of star exe
star_path: /home/annbrown/STAR/bin/Linux_x86_64_static/STAR
#########################

# extra_star_parameters_first_pass:
#   alignEndsType: EndToEnd
#   quantMode: GeneCounts
#   outSAMtype: None
#   outSJfilterReads: Unique 

extra_star_parameters:
  outSAMattributes: MD NH
  quantMode: GeneCounts
  outSAMtype: BAM Unsorted 
  outSAMunmapped: Within
  twopassMode: Basic


#########################
##SAMTOOLS PARAMETERS - ALIGNMENT HERE######
#########################
samtools_path: /share/apps/genomics/samtools-1.3.1/bin/samtools



#path to the multiqc file ######HOPEFULLY THIS WILL BE REPLACED BY A SHARE LOCATION, CURRENTLY JUST INSTALLED ON MY HOMEDRIVE
multiqc_path: /home/annbrown/.local/bin/multiqc
###for any additional multiqc runtime commands, if you want them it would be something like --cl_config "qualimap_config: { general_stats_coverage: [20,40,200] }", otherwise leave the parameter blank
multiqc_configparams: ""