######UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
######UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
######UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
#path to a csv with the follwing format:
#sample_name,unit, fast1,fast2
# # # # if the data is single end leave the fast2 column blank
# sampleCSVpath: /SAN/vyplab/alb_projects/data/muscle/wide_fastq.csv
# end_type: pe
# species: "human"
# #you can leave this blank for paired end
# feature_counts_strand_info: ""
# #always end paths with a trailing slash, or there will be errors :)
# fastqc_output_folder: /SAN/vyplab/alb_projects/data/muscle/analysis/fastqc/
# fastp_trimmed_output_folder: /SAN/vyplab/alb_projects/data/muscle/analysis/fastp_trimmed_again/
# star_output_folder: /SAN/vyplab/alb_projects/data/muscle/analysis/STAR_aligned/
# merged_fastq_folder: /SAN/vyplab/alb_projects/data/muscle/analysis/merged_fastqs/
# feature_counts_output_folder: /SAN/vyplab/alb_projects/data/muscle/analysis/feature_counts/
#

# # # #####UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
# # # #####UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
# sampleCSVpath: /SAN/vyplab/alb_projects/data/4su_tdp_f210i/fastq_locations_4su.csv
# end_type: se
# readLen: 75
# #mouse or human
# species: "mouse"
# ####use "infer_experiment.py" from  /SAN/vyplab/alb_projects/tools/RSeQC/bin/infer_experiment.py on the aligned bams if you are unsure
# feature_counts_strand_info: "-s 1"
#
#
# fastqc_output_folder: /SAN/vyplab/alb_projects/data/4su_tdp_f210i/fastqc/
# fastp_trimmed_output_folder: /SAN/vyplab/alb_projects/data/4su_tdp_f210i/fastp_trimmed/
# star_output_folder: /SAN/vyplab/alb_projects/data/4su_tdp_f210i/STAR_aligned_redone/
# merged_fastq_folder: /SAN/vyplab/alb_projects/data/4su_tdp_f210i/merged_fastqs/
# feature_counts_output_folder: /SAN/vyplab/alb_projects/data/4su_tdp_f210i/feature_counts/
# # #####UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
# #####UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
sampleCSVpath: /SAN/vyplab/alb_projects/data/original_data_tdp_mefs/original_mefs.csv
end_type: pe
readLen: 50
#mouse or human
species: "mouse"
####use "infer_experiment.py" from  /SAN/vyplab/alb_projects/tools/RSeQC/bin/infer_experiment.py on the aligned bams if you are unsure
feature_counts_strand_info: "-s 2"

#
fastqc_output_folder: /SAN/vyplab/alb_projects/data/original_data_tdp_mefs/fastqc/
fastp_trimmed_output_folder: /SAN/vyplab/alb_projects/data/original_data_tdp_mefs/fastp_trimmed/
star_output_folder: /SAN/vyplab/alb_projects/data/original_data_tdp_mefs/STAR_aligned/
merged_fastq_folder: /SAN/vyplab/alb_projects/data/original_data_tdp_mefs/merged_fastqs/
feature_counts_output_folder: /SAN/vyplab/alb_projects/original_data_tdp_mefs/herzog_2017/feature_counts/
#

######IF YOU DON'T KNOW WHAT YOU'RE DOING DON'T FIDDLE WITH THESE NEXT LINES#########
######IF YOU DON'T KNOW WHAT YOU'RE DOING DON'T FIDDLE WITH THESE NEXT LINES#########
######IF YOU DON'T KNOW WHAT YOU'RE DOING DON'T FIDDLE WITH THESE NEXT LINES#########
STAR_indices: /SAN/vyplab/vyplab_reference_genomes/STAR/

#########################
##FASTQC PARAMETERS######
#########################

#path to the fastqc executable
fastqc_path: /share/apps/genomics/FastQC-0.11.8/fastqc



#########################
##FASTP PARAMETERS - TRIMMING HERE######
#########################
fastp_path: /SAN/vyplab/alb_projects/tools/fastp

#quality trimming is debated, and harsh cutoff can effect expression, using a soft quality trim of 10 based on this paper
#https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-0956-2
#use this flag if there are UMI's present, if there are, there should be a file with fastq & umi fastq present, otherwise
#additional parameters you might want to add on
fastp_parameters:
  qualified_quality_phred: 10
  #use this flag if there are UMI's present, if there are, there should be a file with fastq & umi fastq present, otherwise
  #leave this flag as an empty string: ""
  #umi: ""
  #umi_loc: /SAN/vyplab/IoN_RNAseq/Bilal_Muscle_biopsies/analysis/fastqc/


#########################
##STAR PARAMETERS - ALIGNMENT HERE######
#########################
#location of star exe
star_path: /home/annbrown/STAR/bin/Linux_x86_64_static/STAR
#########################

extra_star_parameters:
  outSAMattributes: MD NH XS
  quantMode: GeneCounts
  outSAMtype: BAM Unsorted
  outSAMunmapped: Within
  twopassMode: Basic
  alignEndsType: EndToEnd



#########################
##SAMTOOLS PARAMETERS - ALIGNMENT HERE######
#########################
samtools_path: /share/apps/genomics/samtools-1.9/bin/samtools

#########################
##FEATURECOUNTS PARAMETERS - COUNTING HERE######
#########################
feature_counts_path: /SAN/vyplab/alb_projects/tools/subread-1.6.4-Linux-x86_64/bin/featureCounts
#path to the multiqc file
multiqc_path: /share/apps/python-3.6.4-shared/bin/multiqc
###for any additional multiqc runtime commands, if you want them it would be something like --cl_config "qualimap_config: { general_stats_coverage: [20,40,200] }", otherwise leave the parameter blank
multiqc_configparams: ""
